export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const FETCH_MEDIA = "FETCH_MEDIA";
export const FETCH_MEDIA_SUCCESS = "FETCH_MEDIA_SUCCESS";
export const FETCH_MEDIA_FAILURE = "FETCH_MEDIA_FAILURE";
export const UPLOAD_MEDIA = "UPLOAD_MEDIA";
export const UPLOAD_MEDIA_SUCCESS = "UPLOAD_MEDIA_SUCCESS";
export const UPLOAD_MEDIA_FAILURE = "UPLOAD_MEDIA_FAILURE";

export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";
export const FETCH_POST = "FETCH_POST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

export const FETCH_PUBLIC_POSTS = "FETCH_PUBLIC_POSTS";
export const FETCH_PUBLIC_POSTS_SUCCESS = "FETCH_PUBLIC_POSTS_SUCCESS";
export const FETCH_PUBLIC_POSTS_FAILURE = "FETCH_PUBLIC_POSTS_FAILURE";
export const FETCH_PUBLIC_POST = "FETCH_PUBLIC_POST";
export const FETCH_PUBLIC_POST_SUCCESS = "FETCH_PUBLIC_POST_SUCCESS";
export const FETCH_PUBLIC_POST_FAILURE = "FETCH_PUBLIC_POST_FAILURE";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";

export const FETCH_SETTING = "FETCH_SETTING";
export const FETCH_SETTING_SUCCESS = "FETCH_SETTING_SUCCESS";
export const FETCH_SETTING_FAILURE = "FETCH_SETTING_FAILURE";
